### ISSUE TITLE
[BUG] Motion Sensor not usable in Routines

### ISSUE THREAD

**Issue by Shirk** [csuermann/node-red-contrib-virtual-smart-home#130] opened 2022-03-31 18:09 UTC
I'm trying to create a routine with a vsh device configured as "Motion Sensor" but Alexa tells me "This Device is not currently supported". (same as #103)

**To Reproduce**
1. setup vsh
2. add a virtual device to your flow
3. set the devices name and configure it's type as "Motion Sensor"4. 
4. deploy the flow

**Expected behavior**
The device should appear in Alexa and be usable as a motion sensor in routines.

**Screenshots**

![image](https://user-images.githubusercontent.com/304352/161121572-16d8eeca-036e-4330-b3e1-67d077a1d36b.png)
<img width="612" alt="image" src="https://user-images.githubusercontent.com/304352/161121615-027d4fb4-728e-47c6-8ee0-dbb56b0d30ec.png">

**Environment (please complete the following information):**
 - virtual-smart-home version: 2.13.1
 - Node-RED version: 2.2.2

~~**Additional context**~~

**Comment by bwims** [comment] 2022-04-06 17:22
I have the same problem.  I was going to give a motion detector a try because my doorbell had stopped working.

I can only think that the Amazon developers have screwed things up for skill developers again! :-(

**Comment by csuermann** [comment] 2022-04-06 18:09
Sorry for the trouble, everyone! I didn't change anything, hence the hiccup is probably caused by Amazon.

**Comment by bwims** [comment] 2022-04-07 08:57
Just wondering, do they have developer support forums, or would that be a
"premium feature"?  The community support forums they provide to Joe public
are laughable....

**Comment by bwims** [comment] 2022-04-07 11:05
Blow me down!  Both contacts AND motion sensor are now accepted in routines
today!

Sadly, the Doorbell is still broken.

B.

**Comment by csuermann** [comment] 2022-07-10 05:47
closing as Amazon appears to have solved the issue for motion and contact sensors.

**Closed by csuermann** 2022-07-10 05:47 UTC
Labels: bug
