### ISSUE TITLE
The service (on the server) changes the connection property thingId

### ISSUE THREAD

**Issue by nhintro** [csuermann/node-red-contrib-virtual-smart-home#146] opened 2022-08-21 09:38 UTC
**Hello Mr. Suermann,**
We are using your product node-red node “node-red-contrib-virtual-smart-home” and we found out that the service changes the connection thingId after we register our devices and causes the next day that registered virtual devices cannot work any more…
**after one day or sometime later it happens on the side of the service (on the server) changes the value of the property thingId:**"vsht-6ed8c0c8-136c-4451-94d3-961225f78138" of the connection for registered virtual devices and cause the virtual devices does not work and come on the Alexa echo device: “_please check the network connect of the device …_.”, also in another case the echo device saying “_OK…_”  **for another device in the same network but no action undertaken on the device,**
But if we create a new virtual device, it gets a new new thingId:" vsht-6ed8c0c8-136c-4451-94d3-xxxxxxxxxx”, which is different than the one existing!,  and the new node work but the existing ones still not work any more
**Note that:**
a.	 all registered devices list in node-red have gray back ground
b.	All device in the node-red flow page show green (online) 

**we use the following service:**
lwaClientId=amzn1.application-oa2-client.3f1bb07133854b078261ad43f2484c18
backendUrl=https://kfd5m4a21f.execute-api.eu-west-1.amazonaws.com/dev

**My questions:**
what is the solution to avoid the value change of the property thingId for the connection of the registered virtual devices? 
is there any other stable business node-red-contrib-virtual-smart-home version or a stable business service for the virtual device node?
 
Nasir Hassan

**Comment by csuermann** [comment] 2022-08-21 10:52
Hi @nhintro!
I'm trying to wrap my head around what you describe, but there is only one place where the thingId is created, and that is once the account linking process (using the `code` displayed in Node-RED) is completed.

To troubleshoot this issue further, I have a few questions for you:

1. Do you have _more than one_ VSH connection configured?
2. Is there anything special in your setup that could potentially change settings in your Node-RED instance (e.g. a process that restores a backup)

**Comment by nhintro** [comment] 2022-08-21 18:56
**Hello Mr. Suermann,**
 
thank you for swift reply,

yes that should be the right way as you said _"there is only one place where the thingId is created, and that is once the account linking process (using the code displayed in Node-RED) is completed."_ 
but what happened is that after on day or some time from the account linking process ,.... the service (at the server) changes the thingId  and after it the existing virtual devices not works any more but new created virtual device works... and if you check the node-red JSON file  you will find that the **thingId  has new value** , even you did not do any new  connection or any new account linking process.

**Questions & answers:**

**Do you have more than one VSH connection configured?**
we have only  one VSH connection configured on the production raspberry but on other node-red on a testing raspberry we have another  VSH connection configured.
**and both connections use the following service endpoint:**
lwaClientId=amzn1.application-oa2-client.3f1bb07133854b078261ad43f2484c18
backendUrl=https://kfd5m4a21f.execute-api.eu-west-1.amazonaws.com/dev
**2. Is there anything special in your setup that could potentially change settings in your Node-RED instance (e.g. a process that restores a backup).**
no, we do not  a setup cloud might effect setting .

thank you for your support
Nasir Hassan

**Comment by nhintro** [comment] 2022-08-21 19:26
![virtualdevice - connection thingId-Postman](https://user-images.githubusercontent.com/111676831/185807579-e964b0ee-93c5-4fa8-8ef0-a988a4c26137.png)

**Comment by csuermann** [comment] 2022-08-22 06:09
Hi Nasir,

Thanks for providing additional information. Mind you, the `/devices` endpoint returns _all VSH devices linked to your Amazon account_, regardless via which thingId they are connected. In the VSH connection screen, devices belonging to the current connection have a white, otherwise a grey background.

To debug your issue further you could try to switch on `debug` mode which will log all MQTT messages to the Node-RED CLI console.

My hunch is that the problem might have to do with your _other_ testing raspberry, so you might want to enable debug mode there as well and compare both logs.

Speaking of your testing raspberry: Did you install and configure VSH on there from scratch or did you import any settings from your other raspberry?

**Comment by csuermann** [comment] 2022-08-22 15:50
Hi Nasir,

> is there is service expire time for thingId?

No

> do we need for a license?

No

> do we work on service endpoint for a development environment (we see it ending with /dev?)

Although misleading, `/dev` is actually the production environment, so all good here.

> do we have a conflict with backendUrl because we have this backendUrl from one of your code example in GitHub ???

You're not running your own VSH backend, are you? The backend ULR you posted is the right one if you're using my hosted backend (the default).

> do we have a conflict with waClientId because we have this waClientId from one of your code example in GitHub , and that we must make our own waClientId???

You only need your own `LwaClientId` if you're running your own instance of the [VSH backend](https://github.com/csuermann/virtual-smart-home).

I'm still puzzled by the issue you describe. You're the first person ever reporting such strange behaviour and I'm quite certain that the root cause lies outside of VSH itself.

**Comment by csuermann** [comment] 2022-08-29 10:05
Hi Nasir,

These values are only needed by the Node-RED frontend for displaying the list of registered devices. They have no relevance regarding Alexa connectivity.

**Comment by csuermann** [comment] 2022-10-04 08:38
Closing this issue for now. Feel free to reopen it if needed.

**Closed by csuermann** 2022-10-04 08:38 UTC
