### ISSUE TITLE
Reporting msg.payload.device

### ISSUE THREAD

**Issue by dynamicdave1515** [csuermann/node-red-contrib-virtual-smart-home#254] opened 2024-04-02 19:22 UTC
### Problem Statement

Would it be possible for your VSH node to report the name of the device that uttered the command?
If it did, then I could send a message to the appropriate Alexa Dot giving verbal feedback.
Really enjoying using VSH in my Node-RED flows.

**Comment by csuermann** [comment] 2024-04-03 13:58
Duplicate of #253, #197, #202, #70 and others.

Please note that it is technically not possible to implement this feature due to limitations of the Alexa Smart Home API. However, consider the workaround described in [FAQ #2](https://github.com/csuermann/node-red-contrib-virtual-smart-home#faq). Hope that works for you.

**Closed by csuermann** 2024-04-03 13:58 UTC
Labels: enhancement
