### ISSUE TITLE
Can't upgrade to 4.X version

### ISSUE THREAD

**Issue by lslblues** [csuermann/node-red-contrib-virtual-smart-home#246] opened 2024-02-25 01:06 UTC
### Bug Description

I am a Pro subscriber currently running 3.0.12 with Node-red 3.1.5, NPM 8.19.3, node 16.20.2, and Raspbian 10.  Others have successfully upgraded to 4.1.4, but I get errors for 4.1.7
Is VSH 4.14 or 4.1.4?  Mine is trying to pull 4.1.7 and I get this error.
24-02-25T00:32:48.918Z [err]  Not compatible with your version of node/npm: [debounce@2.0.0](mailto:debounce@2.0.0)
2024-02-25T00:32:48.919Z [err] npm
2024-02-25T00:32:48.919Z [err] ERR! notsup
2024-02-25T00:32:48.919Z [err]  Not compatible with your version of node/npm: [debounce@2.0.0](mailto:debounce@2.0.0)
2024-02-25T00:32:48.920Z [err] npm
2024-02-25T00:32:48.920Z [err] ERR! notsup Required: {"node":">=18"}
2024-02-25T00:32:48.920Z [err] npm ERR!
2024-02-25T00:32:48.920Z [err]  notsup Actual:   {"npm":"8.19.3","node":"v16.20.2"}

And these if I try to pul 4.1.4
[pi@coachproxyos:~/.node-red](mailto:pi@coachproxyos:~/.node-red) $ npm install  [node-red-contrib-virtual-smart-home@4.1.4](mailto:node-red-contrib-virtual-smart-home@4.1.4)
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'fast-unique-numbers@9.0.0',
npm WARN EBADENGINE   required: { node: '>=18.2.0' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.3' }
npm WARN EBADENGINE }

### To Reproduce

upgrade 3.0.12 to 4.1.4 or 4.1.7

### Expected behavior

Should upgrade

### Virtual-Smart-Home Version

3.0.12

### Node-RED Version

3.1.5

### Node.js Version

16.20.2

### Plan

PRO

**Comment by csuermann** [comment] 2024-02-25 07:19
Hi @lslblues!

> Required: {"node":">=18"}

Looks like you're still on Node.js 16. Can you update to version 18? Node 16 reached end of life in 2023 and should no longer be used.

Duplicate of #243 and #241

**Comment by csuermann** [comment] 2024-02-25 09:43
Actually, after reviewing the transient dependencies responsible for the strict requirement of Node 18, I've concluded that mandating a Node.js update wasn't warranted.

**As a result, I've released VSH v.4.1.10, which restores compatibility with Node.js 16.**

Following the anticipated release of Node-RED 4.0, I'll publish a new major version of VSH that incorporates updates for all dependencies.

**Comment by rlust** [comment] 2024-02-25 12:37
I just tried to update my older node red to this release and get the following errors.

2024-02-25T12:33:44.184Z Install : node-red-contrib-virtual-smart-home 4.1.10

2024-02-25T12:33:44.798Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-virtual-smart-home@4.1.10
2024-02-25T12:33:50.495Z [err] npm WARN config production Use `--omit=dev` instead.
2024-02-25T12:34:10.948Z [err] npm ERR! code EBADENGINE
2024-02-25T12:34:10.948Z [err] npm ERR! engine Unsupported engine
2024-02-25T12:34:10.948Z [err] npm ERR! engine Not compatible with your version of node/npm: fast-unique-numbers@9.0.0
2024-02-25T12:34:10.948Z [err] npm ERR! notsup Not compatible with your version of node/npm: fast-unique-numbers@9.0.0
2024-02-25T12:34:10.948Z [err] npm ERR! notsup Required: {"node":">=18.2.0"}
2024-02-25T12:34:10.948Z [err] npm ERR! notsup Actual:   {"npm":"8.19.4","node":"v16.20.2"}
2024-02-25T12:34:10.948Z [err] 
2024-02-25T12:34:10.948Z [err] npm ERR! A complete log of this run can be found in:
2024-02-25T12:34:10.948Z [err] npm ERR!     /coachproxy/home/pi/.npm/_logs/2024-02-25T12_33_50_159Z-debug-0.log
2024-02-25T12:34:11.127Z rc=1

**Comment by AleksCee** [comment] 2024-02-25 12:47
Same issue here. The nodered docker has node 16 as base, so can‘t update without migrate from docker to native which is no option for me.

**Comment by csuermann** [comment] 2024-02-25 13:37
> Same issue here. The nodered docker has node 16 as base, so can‘t update without migrate from docker to native which is no option for me.

@AleksCee, would switching to [nodered/node-red:latest-18](https://hub.docker.com/layers/nodered/node-red/latest-18/images/sha256-2a83885d1cff945d3395414b297ed0c48278f9336de8f91e598dd47ef38fbab6?context=explore) be an option for you?

**Comment by AleksCee** [comment] 2024-02-25 15:56
@csuermann I have just switched to latest-18 and seems to work. Sorry I have thought that the latest is the latest in any case. Nodered recommended node 18/20 but the latest image has 16… hmmm ok, now I’m using 18 :-) I hope not to forget to change this in the future.

**Comment by csuermann** [comment] 2024-02-25 16:36
@rlust, for some reason npm seems to ignore the [overrides](https://github.com/csuermann/node-red-contrib-virtual-smart-home/blob/master/package.json#L54) section defined in `package.json`.

In any case, you should be able to install VSH manually by executing

```
npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-virtual-smart-home
```

without the `--engine-strict` flag which is added by default when triggering the installation through the Node-RED UI.

This will generate a warning instead of an error and the installation will succeed.

**Comment by lslblues** [comment] 2024-02-26 00:48
Here is the error I get trying to update to the latest version.

-----------------------------------------------------------
2024-02-26T00:42:27.958Z Install : node-red-contrib-virtual-smart-home 4.1.10

2024-02-26T00:42:28.067Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict ***@***.******@***.***>
2024-02-26T00:42:30.170Z [err] npm
2024-02-26T00:42:30.172Z [err]  WARN
2024-02-26T00:42:30.172Z [err]  config production Use `--omit=dev` instead.
2024-02-26T00:42:37.087Z [err] npm
2024-02-26T00:42:37.088Z [err]  ERR! code
2024-02-26T00:42:37.088Z [err]  EBADENGINE
2024-02-26T00:42:37.096Z [err] npm
2024-02-26T00:42:37.096Z [err] ERR! engine
2024-02-26T00:42:37.097Z [err]  Unsupported engine
2024-02-26T00:42:37.097Z [err] npm
2024-02-26T00:42:37.098Z [err] ERR! engine Not compatible with your version of node/npm: ***@***.******@***.***>
2024-02-26T00:42:37.099Z [err] npm ERR!
2024-02-26T00:42:37.099Z [err] notsup Not compatible with your version of node/npm: ***@***.******@***.***>
2024-02-26T00:42:37.099Z [err] npm ERR! notsup Required: {"node":">=18.2.0"}
2024-02-26T00:42:37.099Z [err] npm ERR! notsup Actual:   {"npm":"8.15.0","node":"v16.17.1"}
2024-02-26T00:42:37.108Z [err]
2024-02-26T00:42:37.109Z [err] npm ERR!
2024-02-26T00:42:37.109Z [err]  A complete log of this run can be found in:
2024-02-26T00:42:37.109Z [err] npm ERR!     /coachproxy/home/pi/.npm/_logs/2024-02-26T00_42_30_059Z-debug-0.log
2024-02-26T00:42:37.127Z rc=1


From: Cornelius Suermann ***@***.***>
Date: Sunday, February 25, 2024 at 6:37 AM
To: csuermann/node-red-contrib-virtual-smart-home ***@***.***>
Cc: lslblues ***@***.***>, Mention ***@***.***>
Subject: Re: [csuermann/node-red-contrib-virtual-smart-home] Can't upgrade to 4.X version (Issue #246)

Same issue here. The nodered docker has node 16 as base, so can‘t update without migrate from docker to native which is no option for me.

@AleksCee<https://github.com/AleksCee>, would switching to nodered/node-red:latest-18<https://hub.docker.com/layers/nodered/node-red/latest-18/images/sha256-2a83885d1cff945d3395414b297ed0c48278f9336de8f91e598dd47ef38fbab6?context=explore> be an option for you?

**Comment by rlust** [comment] 2024-02-26 03:55
I tried your suggestion on terminal and get the following errors.

pi@rvc:~ $ npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-virtual-smart-home
npm WARN config production Use `--omit=dev` instead.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'fast-unique-numbers@9.0.0',
npm WARN EBADENGINE   required: { node: '>=18.2.0' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }

**Comment by csuermann** [comment] 2024-02-26 07:15
> I tried your suggestion on terminal and get the following _errors_.

@rlust, these are not _errors_ but _warnings_ and the installation should still have succeeded. Can you confirm?

**Comment by lslblues** [comment] 2024-02-26 14:54
I ran that in a term window, got the warnings, and my VSH version in node-red still shows 3.0.12

From: Cornelius Suermann ***@***.***>
Date: Monday, February 26, 2024 at 12:15 AM
To: csuermann/node-red-contrib-virtual-smart-home ***@***.***>
Cc: lslblues ***@***.***>, Mention ***@***.***>
Subject: Re: [csuermann/node-red-contrib-virtual-smart-home] Can't upgrade to 4.X version (Issue #246)

I tried your suggestion on terminal and get the following errors.

@rlust<https://github.com/rlust>, these are not errors but warnings and the installation should still have succeeded. Can you confirm?

**Comment by csuermann** [comment] 2024-02-26 15:17
Even after restarting Node-RED?

**Comment by lslblues** [comment] 2024-02-26 15:23
I see the problem.  Node-red is running as a service, and when I update from cmd line, its updating it in a different directory.  So the version in 1 directory is now 4.1.11, but node-red instance running as aservice is using the version in the other directory, 3.0.12, and the palette manager in node-red won’t update – it gives the errors, not warnings.

From: Cornelius Suermann ***@***.***>
Date: Monday, February 26, 2024 at 8:17 AM
To: csuermann/node-red-contrib-virtual-smart-home ***@***.***>
Cc: lslblues ***@***.***>, Mention ***@***.***>
Subject: Re: [csuermann/node-red-contrib-virtual-smart-home] Can't upgrade to 4.X version (Issue #246)

Even after restarting Node-RED?

**Comment by csuermann** [comment] 2024-02-26 15:36
> when I update from cmd line, its updating it in a different directory.

Can you issue the install command from the right directory?

**Comment by lslblues** [comment] 2024-02-26 15:59
Finally got it to do it. Had to add @4.1.10 to end of virtual-smart-home

From: Cornelius Suermann ***@***.***>
Date: Monday, February 26, 2024 at 8:36 AM
To: csuermann/node-red-contrib-virtual-smart-home ***@***.***>
Cc: lslblues ***@***.***>, Mention ***@***.***>
Subject: Re: [csuermann/node-red-contrib-virtual-smart-home] Can't upgrade to 4.X version (Issue #246)

when I update from cmd line, its updating it in a different directory.

Can you issue the install command from the right directory?

**Comment by csuermann** [comment] 2024-02-27 07:19
VSH v4.1.12 adds a `npm-shrinkwrap.json` file to explicitly pin dependencies. With that, compatibility with Node 16 should finally be restored.

**Closed by csuermann** 2024-02-27 07:19 UTC
Labels: bug
